services:
  eventclean-db:
    image: postgres:15
    container_name: arquitetura_limpa
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - arch-db-data:/var/lib/postgresql/data

volumes:
  arch-db-data: